### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by lordofscripts** [NuGet/json-ld.net#19] opened 2017-04-25 17:39 UTC
Well, it seems like a library that does something with JSON-LD but there is no documentation whatsoever. I install the NuGet package, put my using statement and then what?

**Comment by emgarten** [comment] 2017-04-25 19:06
@lordofscripts I agree, this project really needs some examples and docs. 

Dupe of https://github.com/NuGet/json-ld.net/issues/11

**Closed by emgarten** 2017-04-25 19:06 UTC
